repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: "mkdocs.*\\.yml$"
      - id: debug-statements
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        types_or: [python, pyi, jupyter]
        args: [--fix, --config, pyproject.toml]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
        args: [--config, pyproject.toml]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        types: [jupyter]
        language_version: python3
